# Generated by Django 5.2.9 on 2026-02-12 06:29

import django.db.models.deletion
import polls.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('access_code', models.CharField(db_index=True, default=polls.models.generate_access_code, max_length=8, unique=True, verbose_name='Код доступа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('allow_multiple_submissions', models.BooleanField(default=False, help_text='Если выключено — пользователь или аноним может пройти опрос только один раз.', verbose_name='Разрешить повторное прохождение')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Если указано — участник должен пройти опрос за указанное количество минут. Оставьте пустым — нет ограничения.', null=True, verbose_name='Ограничение времени (минуты)')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_polls', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Будет отображаться участникам опроса', max_length=500, verbose_name='Текст вопроса')),
                ('kind', models.CharField(choices=[('TEXT', 'Текстовый ответ'), ('SINGLE', 'Одиночный выбор'), ('MULTI', 'Множественный выбор')], default='TEXT', max_length=10, verbose_name='Тип вопроса')),
                ('order', models.PositiveIntegerField(default=1, help_text='Чем меньше число — тем выше вопрос (начинается с 1)', verbose_name='Порядок')),
                ('is_test_question', models.BooleanField(default=False, help_text='Если включено — можно будет указать правильные варианты ответов.', verbose_name='Тестовый вопрос')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, help_text='Отметьте, если это правильный вариант (только для тестовых вопросов).', verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Набрано баллов')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Всего вопросов с проверкой')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Ключ сессии')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='polls.poll', verbose_name='Опрос')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ участника',
                'verbose_name_plural': 'Ответы участников',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='answers', to='polls.choice', verbose_name='Выбранные варианты')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='Вопрос')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.submission', verbose_name='Ответ на опрос')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
            },
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('poll', 'order'), name='unique_order_per_poll'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_answer_per_submission_question'),
        ),
    ]
