# Generated by Django 5.2.9 on 2026-01-01 15:14

import django.db.models.deletion
import polls.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerchoice',
            options={'verbose_name': 'Выбранный вариант', 'verbose_name_plural': 'Выбранные варианты'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-created_at'], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ответ участника', 'verbose_name_plural': 'Ответы участников'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, related_name='answers', through='polls.AnswerChoice', to='polls.choice', verbose_name='Выбранные варианты'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.submission', verbose_name='Ответ на опрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_value',
            field=models.TextField(blank=True, verbose_name='Текстовый ответ'),
        ),
        migrations.AlterField(
            model_name='answerchoice',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='polls.answer', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answerchoice',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='polls.choice', verbose_name='Вариант'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='access_code',
            field=models.CharField(db_index=True, default=polls.models.generate_access_code, max_length=8, unique=True, verbose_name='Код доступа'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_polls', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_test_question',
            field=models.BooleanField(default=False, help_text='Если включено — можно будет указать правильные варианты ответов.', verbose_name='Тестовый вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('TEXT', 'Текстовый ответ'), ('SINGLE', 'Одиночный выбор'), ('MULTI', 'Множественный выбор')], default='TEXT', max_length=10, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Чем меньше число — тем выше вопрос (начинается с 1)', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.poll', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='polls.poll', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Набрано баллов'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего вопросов с проверкой'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
